version: "3.8"

volumes:
  mariadb_data:
  romm_resources:
  romm_redis_data:
  syncthing_config:

services:
  romm-db:
    image: mariadb:latest
    container_name: romm-db
    restart: unless-stopped
    environment:
      MARIADB_ROOT_PASSWORD: ${MARIADB_ROOT_PASSWORD}
      MARIADB_DATABASE: ${DB_NAME}
      MARIADB_USER: ${DB_USER}
      MARIADB_PASSWORD: ${DB_PASSWD}
    volumes:
      - mariadb_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
      start_period: 30s
      interval: 10s
      timeout: 5s
      retries: 5

  romm:
    image: rommapp/romm:latest
    container_name: romm
    restart: unless-stopped
    depends_on:
      romm-db:
        condition: service_healthy
      init-romm:
        condition: service_completed_successfully
    environment:
      DB_HOST: romm-db
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWD: ${DB_PASSWD}

      ROMM_AUTH_SECRET_KEY: ${ROMM_AUTH_SECRET_KEY}

      # Metadata providers (optionnels, mais recommandés)
      IGDB_CLIENT_ID: ${IGDB_CLIENT_ID:-}
      IGDB_CLIENT_SECRET: ${IGDB_CLIENT_SECRET:-}
      SCREENSCRAPER_USER: ${SCREENSCRAPER_USER:-}
      SCREENSCRAPER_PASSWORD: ${SCREENSCRAPER_PASSWORD:-}
      RETROACHIEVEMENTS_API_KEY: ${RETROACHIEVEMENTS_API_KEY:-}
      STEAMGRIDDB_API_KEY: ${STEAMGRIDDB_API_KEY:-}

      # Optionnel (selon tes usages)
      HASHEOUS_API_ENABLED: ${HASHEOUS_API_ENABLED:-true}

      SCAN_TIMEOUT: ${SCAN_TIMEOUT:-14400} # 	Timeout for the background scan/rescan tasks (in seconds) (default: 4 hours)
    volumes:
      - romm_resources:/romm/resources
      - ${SAVES_SYNC_PATH}:/romm/resources/saves # To sync game saves via Syncthing.
      - romm_redis_data:/redis-data
      - ${ROMM_LIBRARY_PATH}:/romm/library
      - ${ROMM_ASSETS_PATH}:/romm/assets
      - ${ROMM_CONFIG_PATH}:/romm/config
    ports:
      - "${ROMM_PORT:-8080}:8080"

  vpn:
    container_name: romm_vpn
    image: dperson/openvpn-client:latest
    cap_add:
      - net_admin # required to modify network interfaces
    privileged: true
    restart: unless-stopped
    volumes:
      - /dev/net:/dev/net:z # tun device
      - ${VPN_CONFIG_PATH}:/vpn # OpenVPN configuration
    security_opt:
      - label:disable
    ports:
      - "${DELUGE_WEB_PORT:-8112}:8112" # port for deluge web UI to be reachable from local network
    command: '-f "" -r ${VPN_LOCAL_CIDR:-192.168.1.0/24}' # enable firewall and route local network traffic

  deluge:
    container_name: romm_deluge
    image: linuxserver/deluge:latest
    restart: unless-stopped
    network_mode: service:vpn
    depends_on:
      - vpn
    environment:
      - PUID=${PUID:-1000} # default user id, defined in .env
      - PGID=${PGID:-1000} # default group id, defined in .env
      - TZ=${TZ:-Europe/Paris} # timezone, defined in .env
    volumes:
      - ${DELUGE_DOWNLOADS_PATH}:/downloads # downloads folder
      - ${DELUGE_CONFIG_PATH}:/config # config files

# Too much of a hassle to set up and maintain for now.
# There is an official RFC:
#   "Device Registration and Multi-Protocol Save Synchronization"
# in the works that should make this easier in the future.
# See:
#   https://github.com/rommapp/romm/discussions/2199
  # syncthing:
  #   image: lscr.io/linuxserver/syncthing:latest
  #   container_name: syncthing
  #   restart: unless-stopped
  #   environment:
  #     PUID: ${PUID:-1000}
  #     PGID: ${PGID:-1000}
  #     TZ: Europe/Paris
  #   volumes:
  #     - syncthing_config:/config
  #     # Dossier "serveur" à synchroniser avec tes devices (PC/SteamDeck/Android/etc.)
  #     - ${SAVES_SYNC_PATH}:/data/saves
  #   ports:
  #     - "8384:8384" # UI Web
  #     - "22000:22000/tcp" # Sync
  #     - "22000:22000/udp" # QUIC
  #     - "21027:21027/udp" # Discovery LAN

  init-romm:
    image: alpine:latest
    container_name: init-romm
    environment:
      PUID: ${PUID:-1000}
      PGID: ${PGID:-1000}
    volumes:
      - ${ROMM_LIBRARY_PATH}:/romm/library
      - ./folder_names.csv:/folder_names.csv:ro
      - ./init-romm.sh:/init-romm.sh:ro
    command: ["sh", "/init-romm.sh"]

  group-multidisc:
    image: alpine:latest
    container_name: group-multidisc
    environment:
      PUID: ${PUID:-1000}
      PGID: ${PGID:-1000}
      ROMM_MULTIDISC_PLATFORMS: ${ROMM_MULTIDISC_PLATFORMS:-}
      ROMM_MULTIDISC_DRY_RUN: ${ROMM_MULTIDISC_DRY_RUN:-true}
    volumes:
      - ${ROMM_LIBRARY_PATH}:/romm/library
      - ./group-multidisc.sh:/group-multidisc.sh:ro
    command: ["sh", "/group-multidisc.sh", "/romm/library/roms"]

  cloudflared_romm:
    container_name: cloudflared_romm
    image: cloudflare/cloudflared:latest
    command: tunnel --no-autoupdate run --token ${CLOUDFLARE_TOKEN}
    restart: unless-stopped
